[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
rayon = "1.9.0"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
